const quizData = [
    {
      question: 'Which Twitter user is the Twitter boss, now?',
      a: 'Elon Musk',
      b: 'Donald Trump',
      c: 'Vladimir Putin',
      d: 'Jack Ma',
      e: 'Cristiano Ronaldo',
      correct: 'a',
    },
    {
      question: 'Which twitter user is the former president of the USA?',
      a: 'Elon Musk',
      b: 'Donald Trump',
      c: 'Vladimir Putin',
      d: 'Jack Ma',
      e: 'Cristiano Ronaldo',
      correct: 'b',
    },
    {
      question: 'Which twitter user is known as a former KGB agent?',
      a: 'Donald Trump',
      b: 'Elon Musk',
      c: 'Jack Ma',
      d: 'Vladimir Putin',
      e: 'Cristiano Ronaldo',
      correct: 'd',
    },
    {
      question: 'Which twitter user is a footballer?',
      a: 'Donald Trump',
      b: 'Elon Musk',
      c: 'Cristiano Ronaldo',
      d: 'Vladimir Putin',
      e: 'Jack Ma',
      correct: 'c',
    },
    {
      question: 'Which twitter user is the founder of AliBaba?',
      a: 'Donald Trump',
      b: 'Elon Musk',
      c: 'Cristiano Ronaldo',
      d: 'Vladimir Putin',
      e: 'Jack Ma',
      correct: 'e',
    },
]